### ISSUE TITLE
ISA: Provisional registration workflow not defined

### ISSUE THREAD

**Issue by sureshkrishnan** [ebpffoundation/ebpf-docs#113]
Section 5.1 of draft-ietf-bpf-isa-01 talks about Provisional registrations for BPF instruction conformance groups but does not elaborate further on the procedures. Specifically, I think it would be good to cover the following cases

-> Do we allow conversions from Provisional to Permanent? If so how?
-> Do Provisional registrations timeout after a while if they are not made Permanent?
-> How do we remove Provisional registrations? Are the codepoints freed up?

**Comment by dthaler** [comment]
Fixed in draft-02
