### ISSUE TITLE
ISA: line length in TXT output format

### ISSUE THREAD

**Issue by dthaler** [ebpffoundation/ebpf-docs#123]
>   ** There are 714 instances of too long lines in the document, the longest
>      one being 7 characters in excess of 72.

**Comment by dthaler** [comment]
> On Tue, Apr 09, 2024 at 06:05:15PM -0700, Erik Kline wrote:
> > WRT to the long lines in the table, I asked on Slack for advice and 
> > Amanda Baber came back with this:
> 
> Nice, thanks for asking around.
> 
> > """
> > Replacing “reference” with “section” at the top of the last column 
> > and then removing everything but the numbers might do it. We would 
> > do this anyway, but the authors could include an instruction telling 
> > us to render, e.g., “4.4” as “RFC XXXX, Section 4.4" (per our house style).
> > """

The XML looks fine. I would argue
that the issue is in the XML-to-TXT conversion tool and isn't specific to this draft.
Specifically, it seems to be pretty arbitrary in how it decides the column
width in the TXT version, and columns like the "description" column could
wrap in a way that fit in 72 characters.

Since the RFC editor has ultimate control over the RFC and could do so at
publication time, I'd argue that this issue should not block IETF consensus
and could simply be handled by the RFC editor.  It's fine in my opinion to say
this in the document shepherd writeup.   But I think changing the source to
work around the TXT tool issue has the disadvantage of making the HTML
and PDF versions look worse, which is not a good tradeoff in my view.

Hence I'd propose not addressing this nit in the I-D.

**Comment by dthaler** [comment]
Erik Kline responded:
> Fair enough.  We can leave it for the RFC Editor.

**Comment by ByteLab-David** [comment]
Fine with me as well (will reply on the email thread too)
