### ISSUE TITLE
ISA: items to move from ISA to psABI doc

### ISSUE THREAD

**Issue by dthaler** [ebpffoundation/ebpf-docs#140]
David Vernet <mailto:void@manifault.com> wrote:
> > * src_reg and dst_reg appearing to be 4-bit fields but listed as having
a
> >   valid decimal range of only 0-10 invites questions about R11-R15, I
think.
> 
> Great point. Dave, maybe we should remove the 0-10 specification here?
> That seems like more of a psABI thing.

I agree.

The ISA document also contains this statement:
> The BPF program needs to store the return value into register R0 before doing an EXIT.

Shouldn't that be moved to the psABI too?

**Comment by hawkinsw** [comment]
@dthaler Just dropping in for a +1 here -- I saw the *exact* same issue.

**Comment by dthaler** [comment]
Per discussion at LSF/MM/BPF, there seems to be pushback against moving the "0-10" text, but support for moving the quoted R0 text.  Hence submitted patch https://mailarchive.ietf.org/arch/msg/bpf/RHjXOXRkTc3i5F_wXQjL4MNQvks/

**Comment by dthaler** [comment]
Fixed in draft-03
