### ISSUE TITLE
Github: installing xml2rfc fails

### ISSUE THREAD

**Issue by dthaler** [ebpffoundation/ebpf-docs#23]
https://github.com/ietf-wg-bpf/ebpf-docs/actions/runs/5471462362/jobs/9962624761

**Comment by hawkinsw** [comment]
Not sure if it would help or not, but I have made/published a GitHub action that can do some/all of the post-processing: https://github.com/marketplace/actions/ietf-publisher

Otherwise, let me know if/how I can help!

**Comment by dthaler** [comment]
> Not sure if it would help or not, but I have made/published a GitHub action that can do some/all of the post-processing: https://github.com/marketplace/actions/ietf-publisher
> 
> Otherwise, let me know if/how I can help!

That repository says it works with markdown.  BPF docs are converted from RST not markdown, so I don't think it will help.  Something recently broke, this was working fine earlier.

**Comment by hawkinsw** [comment]
Okay! I am happy to add an RST mode to that action if it would help!

**Comment by hawkinsw** [comment]
Now that I am looking at the error, I recall dealing with a very similar issue when building my action. It had to do with the fact that the runner had an old version of pip, by default. Adding

```
python3 -m pip install --upgrade pip
```

fixed the issue for me. I will fork and attempt to submit a PR. 

Will

**Comment by dthaler** [comment]
Fixed by PR #25
