### ISSUE TITLE
Consider Adopting Industry Standard to Specify Operations in ISA

### ISSUE THREAD

**Issue by hawkinsw** [ebpffoundation/ebpf-docs#34]
There are a few "industrial" ISAs that specify a "language" that they then use to describe the operations of each opcode. Should we use them for describing the operations? 

cc @wbl

Intel: [3.1.1.9 Operation Section](https://cdrdv2.intel.com/v1/dl/getContent/671199)
ARM: [Chapter J1 Armv8 Pseudocode ](https://developer.arm.com/documentation/ddi0487/latest/)

**Comment by dthaler** [comment]
Closing since I think we have WG consensus on the current approach in the document. 
Please reopen if you disagree or want further discussion.

**Comment by hawkinsw** [comment]
I agree! Thanks for following up!
